# Generated by Django 5.1.6 on 2025-02-28 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='education',
            name='major',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='education',
            name='rank',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='skills',
            name='level',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
