# Generated by Django 5.1.6 on 2025-02-28 20:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0002_education_major_education_rank_alter_skills_level'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='education',
            options={'ordering': ['start_date']},
        ),
    ]
