# Generated by Django 5.1.6 on 2025-03-01 01:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0005_alter_experience_options_education_courses_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='award',
            name='school',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='awards', to='resume.education'),
        ),
        migrations.AlterField(
            model_name='project',
            name='school',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='resume.education'),
        ),
    ]
