"""
Django settings for blog project.

Generated by 'django-admin startproject' using Django 5.1.6.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent




# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-r11l7w%3(o-7(rxqfa@opon0z#8@ep1eo2x46nf-a^vw_zd8-)'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['*']

CACHES = {
    'default': {
        'BACKEND': 'django.core.cache.backends.locmem.LocMemCache',
        'LOCATION': 'unique-snowflake',
    }
}

# Application definition
DEFAULT_CHARSET = 'utf-8'
SESSION_EXPIRE_AT_BROWSER_CLOSE = False  # 设置为 False 才不会在浏览器关闭时清除
INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'core',
    'resume',
    'markdownx',
    'taggit',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'blog.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [
            BASE_DIR / 'templates',
        ],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'blog.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/

STATIC_URL = 'static/'
STATICFILES_DIRS = [
    BASE_DIR / 'static',
]

STATIC_ROOT = BASE_DIR / 'staticfiles'

# 媒体文件的基础URL
MEDIA_URL = '/media/'

# 媒体文件的存储路径
MEDIA_ROOT = BASE_DIR / 'media'

# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# # Summernote配置
# SUMMERNOTE_CONFIG = {
#     # 设置编辑器的大小
#     'width': '600px',
#     'height': '1080px',
    
#     # 上传图片大小限制 (单位: 字节)
#     'attachment_filesize_limit': 5 * 1024 * 1024,  # 5MB
    
#     # 上传图片格式限制
#     'attachment_file_types': ['image/jpeg', 'image/jpg', 'image/png', 'image/gif'],
    
#     # 自定义工具栏
#     'toolbar': [
#         ['style', ['style']],
#         ['font', ['bold', 'underline', 'clear']],
#         ['color', ['color']],
#         ['para', ['ul', 'ol', 'paragraph']],
#         ['table', ['table']],
#         ['insert', ['link', 'picture', 'video']],
#         ['view', ['fullscreen', 'codeview', 'help']],
#     ],
    
#     # 上传处理设置
#     'attachment_upload_to': 'summernote/%Y/%m/%d/',
# }

# Markdownx 扩展配置
MARKDOWNX_MARKDOWN_EXTENSIONS = [
    'markdown.extensions.extra',  # 包含多种有用的扩展
    'markdown.extensions.codehilite',  # 代码高亮
    'markdown.extensions.fenced_code',  # 围栏式代码块
    # 其他需要的扩展...
]

MARKDOWNX_MARKDOWN_EXTENSIONS_CONFIGS = {
    'markdown.extensions.codehilite': {
        'linenums': True,  # 显示行号
        'guess_lang': False,  # 不自动猜测语言
        'css_class': 'codehilite',  # CSS 类名
        'pygments_style': 'monokai',  # 指定风格（仅在内部渲染时有效）
    },
}