# Generated by Django 5.1.7 on 2025-03-09 23:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    replaces = [('core', '0001_initial'), ('core', '0002_rename_catetorygory_post_category'), ('core', '0003_alter_post_content'), ('core', '0004_alter_post_content')]

    initial = True

    dependencies = [
        ('resume', '0006_alter_award_school_alter_project_school'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': '日志分类',
                'verbose_name_plural': '日志分类',
                'ordering': ['-order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=255, unique_for_date='created_at')),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('image', models.ImageField(blank=True, default='https://picsum.photos/800/400', null=True, upload_to='images/posts/')),
                ('summary', models.CharField(blank=True, max_length=255)),
                ('tags', models.CharField(max_length=255)),
                ('views', models.PositiveIntegerField(default=0)),
                ('flag', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('draft', '草稿'), ('published', '发布'), ('archived', '归档')], default='draft', max_length=255)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='resume.profile')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='core.category')),
            ],
            options={
                'verbose_name': '日志',
                'verbose_name_plural': '日志',
                'ordering': ['-created_at'],
            },
        ),
    ]
